# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import accountController as acount
from modelos.users import Users


class Ui_Login(object):

    def funcionQueTomadatosyLoguea(self):
        # creamos una instancia del objeto usuario
        usuario = Users()
        # creamos una instancia del objeto login
        logg = acount.Account()
        #tomamos valores de los input
        usr = self.username.text()
        pss = self.password.text()
        # seteamos los parametros al objeto usuario
        usuario.setUsername(usr)
        usuario.setPassword(pss)

        # logueamos al usuario
        logueo = logg.login(usuario)
        print(logueo)


        #cierra la ventana de login
        #self.close()

    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(250, 203)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.dtn_login = QtWidgets.QPushButton(self.centralwidget)
        self.dtn_login.setGeometry(QtCore.QRect(90, 120, 75, 23))
        self.dtn_login.setObjectName("dtn_login")
        #agrega evento de click
        self.dtn_login.clicked.connect(self.funcionQueTomadatosyLoguea)

        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(70, 70, 113, 20))
        self.password.setObjectName("password")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)


        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.dtn_login.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
